doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Domain:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/doctrine_mappings/orm/domain'
                prefix: 'App\Domain'
                alias: App
            Application:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/doctrine_mappings/orm/application'
                prefix: 'App\Application\Entity'
                alias: App
