easy_admin:
    entities:
        - App\Domain\User\Entity\User
        - App\Domain\Client\Entity\Client
        - App\Domain\Scope\Entity\Scope
        - App\Domain\RefreshToken\Entity\RefreshToken
