controllers_api:
    resource: ../../src/Application/Http/Controller/
    type: annotation
    prefix: /api

controllers:
    resource: ../../src/Application/Http/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
