version: '3.4'
services:
  app:
    image: oauth2-server-dev:latest
    volumes:
      - ../..:/var/www/root
      - ~/.ssh:/.ssh
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth
  nginx:
    image: nginx:stable-alpine
    ports:
      - 8000:80
    volumes:
      - ../..:/var/www/root
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    command: [nginx-debug, '-g', 'daemon off;']
