App\Domain\AuthToken\Entity\AuthToken:
    type: entity
    table: auth_tokens
    repositoryClass: App\Infrastructure\Repository\ScopeRepository

    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:
        token: { type: string, unique: true }
        redirectUri: { type: string, unique: true }

    manyToOne:
        client:
            targetEntity: App\Application\Entity\Client
            inversedBy: authTokens
        user:
            targetEntity: App\Application\Entity\User
            inversedBy: authTokens
