App\Domain\Client\Entity\Client:
    type: mappedSuperclass
    table: clients

    id:
        id:
            type: string
            generator: { strategy: UUID }

    fields:
        secret: { type: string }
        host: { type: string }
