App\Domain\Scope\Entity\Scope:
    type: entity
    table: scopes
    repositoryClass: App\Infrastructure\Repository\ScopeRepository

    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:
        name:
            type: string
        description:
            type: string
        defaults:
            type: boolean
