App\Domain\Scope\Entity\Scope:
    type: mappedSuperclass
    table: scopes

    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:
        name: { type: string }
        description: { type: string }
        defaults: { type: boolean }
