App\Domain\User\Entity\User:
    type: mappedSuperclass
    table: users

    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:
        username: { type: string, unique: true, length: 100 }
        email: { type: string, unique: true }
        password: { type: string }
        roles: { type: array }
