App\Domain\User\Entity\User:
    type: mappedSuperclass
    table: users

    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:
        username:
            type: string
            length: 100
            unique: true
        email:
            type: string
            unique: true
        password:
            type: string
        roles:
            type: array
