App\Domain\User\RegistrationData:
    properties:
        username:
            - Length:
                min: 4
        password:
            - Length:
                min: 4
        email:
            - Email:
