App\Application\Entity\User:
    properties:
        username:
            - Length:
                min: 4
        password:
            - Length:
                min: 4
        email:
            - Email
