App\Application\Entity\User:
    type: entity

    oneToMany:
        refreshTokens:
            targetEntity: App\Domain\RefreshToken\Entity\RefreshToken
            mappedBy: user
        authTokens:
            targetEntity: App\Domain\AuthToken\Entity\AuthToken
            mappedBy: user
        clients:
            targetEntity: App\Domain\Client\Entity\Client
            mappedBy: user
