version: '3.4'
services:
  app:
    build: ..
    volumes:
      - ..:/var/www/root
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth
  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ..:/var/www/root
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
